version: '3.7'
services:
  bff-bank:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    networks:
      - servicio_ntt
networks:
  servicio_ntt:
    external: true